
- name: libs
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - python-dev
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
    - libsqlite3-dev
    - libldap2-dev
    - libsasl2-dev
    - libssl-dev
    - libffi-dev
    - libyaml-dev
    - python-pip

- name: virtualenv
  pip: name=virtualenv state=present
