
---
- name: ldap-server
  hosts: ldap-server
  sudo: yes
  roles:
    - apache2
    - ldap-server
    - lam

- name: ldap-client
  hosts: ldap-client
  sudo: yes
  roles:
    - ldap-client

- name: jenkins-server
  hosts: jenkins-server
  sudo: yes
  roles:
    - jenkins

- name: dev-server
  hosts: dev-server
  sudo: yes
  roles:
    - core
    - role: python-dev
      tags: [python]
    - role: rabbitmq
      tags: [rabbitmq]
    - role: redis
      tags: [redis]
    - role: mongodb
      tags: [mongodb]
    - role: nodejs
      tags: [nodejs]
    - role: git
      tags: [git]
    - role: utils
      tags: [utils]
    - role: ssh
      tags: [ssh]
    - role: nginx
      tags: [nginx]
