
- name: add repository
  apt_repository: repo=ppa:chris-lea/node.js
- name: install redis
  apt: name=nodejs state=present
- name: install global package
  npm: name={{item}} global=yes state=present production=yes
  with_items:
    - grunt-cli
    - bower
