- name: group
  group:
    state: present
    name: git
    system: yes

- name: user
  user:
    name: git
    group: git
    state: present

- name: gitolite directory
  file: path=/var/lib/gitolite state=directory owner=git group=git

- name: config
  debconf: name=gitolite3 question={{item.opt}} value={{item.value}} vtype={{item.type}}
  with_items:
    - opt: gitolite3/gitdir
      value: /var/lib/gitolite
      type: string
    - opt: gitolite3/adminkey
      value: /var/lib/gitolite/admin.pub
      type: string
    - opt: gitolite3/gituser
      value: git
      type: string

- name: pub key
  copy: src=admin.pub dest=/var/lib/gitolite/admin.pub owner=git group=git

- name: install gitolite
  apt: name={{item}} state=present
  with_items:
    - gitolite3
    - git-core
